# Generated by Django 3.1.8 on 2023-08-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgraph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='hostname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='mac',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='ro_community',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='rw_community',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='uplink',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
