# Generated by Django 3.1.8 on 2023-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgraph', '0003_auto_20230827_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('edges', models.ManyToManyField(to='netgraph.Edge')),
                ('nodes', models.ManyToManyField(to='netgraph.Node')),
            ],
        ),
    ]
